
SELECT * FROM [TABELA DE PRODUTOS]

SELECT * FROM [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] /* [SUCOS_VENDAS] indica o banco de dados que
a tabela pertence*/

SELECT [CODIGO DO PRODUTO] AS [CÓDIGO], [NOME DO PRODUTO] AS [DESCRITOR], [SABOR]
, [TAMANHO], [EMBALAGEM], [PREÇO DE LISTA] AS [PREÇO LISTA]
 FROM [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] 


SELECT [CODIGO DO PRODUTO] AS [CÓDIGO], [NOME DO PRODUTO] AS [DESCRITOR], [SABOR]
, [TAMANHO], [EMBALAGEM], [PREÇO DE LISTA] AS [PREÇO LISTA]
 FROM [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] <> '1040107'

INSERT INTO [PRODUTOS] ([CÓDIGO], [DESCRITOR], [SABOR], [TAMANHO], [EMBALAGEM], [PREÇO LISTA])
SELECT [CODIGO DO PRODUTO] AS [CÓDIGO], [NOME DO PRODUTO] AS [DESCRITOR], [SABOR]
, [TAMANHO], [EMBALAGEM], [PREÇO DE LISTA] AS [PREÇO LISTA]
 FROM [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] <> '1040107' /* inserindo 
 uma tabela de um banco de dados em outro banco*/


 /*Inclua todos os clientes na tabela CLIENTES baseados nos registros da tabela TABELA DE CLIENTES,
  da base SUCOS_VENDAS.*/

  INSERT INTO [dbo].[CLIENTES]
      ([CPF]  ,[NOME] ,[ENDEREÇO] ,[BAIRRO] ,[CIDADE]  ,[ESTADO]  ,[CEP]
      ,[DATA NASCIMENTO] ,[IDADE] ,[SEXO],[LIMITE DE CRÉDITO]
      ,[VOLUME DE COMPRA],[PRIMEIRA COMPRA])
  SELECT 
	   [CPF] ,[NOME], [ENDERECO 1] AS [ENDEREÇO],  [BAIRRO]
      ,[CIDADE] ,[ESTADO] ,[CEP] ,[DATA DE NASCIMENTO] AS [DATA NASCIMENTO]  ,[IDADE] ,[SEXO] 
	  ,[LIMITE DE CREDITO] AS [LIMITE DE CRÉDITO] ,[VOLUME DE COMPRA]
      ,[PRIMEIRA COMPRA]
  FROM [SUCOS_VENDAS].[dbo].[TABELA DE CLIENTES]
   WHERE [CPF] NOT IN ('1471156710','19290992743','2600586709') /*Excluindo os CPF que já estavam na
   tabela*/
  
